[package]
name = "cozy-spring-jam"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]  # Compile this crate to a dynamic C library.

[dependencies]
godot = { version= "0.2.4" , features = ["api-4-3", "experimental-godot-api"]}
